{"name": "test_assert_error", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n  +1\n  -2", "trace": "self = <testcases.test_testcasepage.TestTestcasePage testMethod=test_assert_error>\n\n    def test_assert_error(self):\n>       assert 1==2\nE       AssertionError: assert 1 == 2\nE         +1\nE         -2\n\ntestcases\\test_testcasepage.py:30: AssertionError"}, "attachments": [{"name": "log", "source": "8bc1a69a-0d8a-431f-b6e6-bbc9b7daadb0-attachment.txt", "type": "text/plain"}], "start": 1629129876761, "stop": 1629129890830, "uuid": "4d8555e7-e94e-439a-a9c1-a3d701e1ab68", "historyId": "3b6475cbab42b2247ca85e4aa4434cc2", "testCaseId": "82df0b8519422fe138049b06c4092da5", "fullName": "testcases.test_testcasepage.TestTestcasePage#test_assert_error", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_testcasepage"}, {"name": "subSuite", "value": "TestTestcasePage"}, {"name": "host", "value": "DESKTOP-RD6RIJS"}, {"name": "thread", "value": "8592-Thread-1"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_testcasepage"}]}