{"name": "test_assert_error", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <testcases.test_testcasepage.TestTestcasePage testMethod=test_assert_error>\n\n    def test_assert_error(self):\n>       assert 1==2\nE       AssertionError: assert 1 == 2\n\ntestcases\\test_testcasepage.py:30: AssertionError"}, "attachments": [{"name": "log", "source": "5b74135f-06ab-4b49-8139-477b889782e6-attachment.txt", "type": "text/plain"}], "start": 1628330918100, "stop": 1628330932141, "uuid": "544853ca-7a8c-4443-ac65-76b1aa74b48c", "historyId": "3b6475cbab42b2247ca85e4aa4434cc2", "testCaseId": "82df0b8519422fe138049b06c4092da5", "fullName": "testcases.test_testcasepage.TestTestcasePage#test_assert_error", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_testcasepage"}, {"name": "subSuite", "value": "TestTestcasePage"}, {"name": "host", "value": "DESKTOP-RD6RIJS"}, {"name": "thread", "value": "7340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_testcasepage"}]}